[workspace]
members = [
  "src/runty8",
  "src/runty8-core",
  "src/runty8-runtime",
  "src/runty8-editor",
  "src/runty8-event-loop",
  "src/runty8-winit",
  "examples",
]
default-members = ["examples"]

resolver = "2"
