[package]
name = "runty8"
version = "0.1.0"
edition = "2021"

[dependencies]
runty8-core = { path = "../runty8-core" }
runty8-runtime = { path = "../runty8-runtime" }
runty8-editor = { path = "../runty8-editor" }
